### PR TITLE
Waiting for turn alerts

### PR DESCRIPTION
**Pull request by kimcarey**
Added "waiting for turn" message for Connect 4 and Snakes game

Screen Shot 2020-02-15 at 2 39 39 PM

### CODE REVIEW

**Comment by YashasG98** [comment]
So, @kimcarey what we expected was that the player waiting in a two player game knows that the other playing is taking time to make his move. So you'll have to edit this to make it work for two players where each player gets the message after he's played his turn and waiting for the other.

image

As opposed to what you see here, the active player should not see the message.

**Review by YashasG98 — CHANGES_REQUESTED** [review]
Note that you'll need to use two different browser windows for the two players to test your working, because we use cookies to maintain user information.

**Comment by kimcarey** [comment]
OK, thanks for clarifying. I will work on revisions.

**Comment by YashasG98** [comment]
I'm closing this pull request, please submit a new one.

**Pull request closed without merging**
